import React,{useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,ChevronRight,ClipboardList,Clock3,Eye,LayoutDashboard,RefreshCw,Route,Snowflake,Truck,X} from 'lucide-react';
import {dispatcherApi} from './api';
import {AllocationResult,DashboardSummary,DispatchOrder,DispatcherPage,DispatchTrip,DispatchVehicle} from './types';
import './dispatcher.css';

const nav=[['dashboard','Dashboard',LayoutDashboard],['orders','Confirmed Orders',ClipboardList],['planning','Daily Planning',Route],['fleet','Fleet & Vehicles',Truck],['live','Active Deliveries',Clock3],['deferred','Deferred Orders',AlertTriangle]] as const;
const time=(value:string)=>new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const tomorrow=()=>new Date(Date.now()+86400000).toISOString();

export const DispatcherPortal:React.FC=()=>{const[page,setPage]=useState<DispatcherPage>('dashboard');return <div className="dp-shell"><aside><div className="dp-brand">WAYPOINT <small>DISPATCH</small></div><p>OPERATIONAL CONTROL</p>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={17}/>{label}</button>)}<div className="dp-shift"><b>Shift Telematics</b><span>Depot Peliyagoda</span><small>Dispatch lanes active</small></div></aside><main><header><div><small>PELIYAGODA DISTRIBUTION CENTRE</small><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><span>{new Date().toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</span></header>{page==='dashboard'?<Dashboard go={setPage}/>:page==='orders'?<Orders go={setPage}/>:page==='planning'?<Planning/>:page==='fleet'?<Fleet/>:page==='live'?<Live/>:<Deferred/>}</main></div>};

function useLoad<T>(path:string){const[data,setData]=useState<T>();const[error,setError]=useState('');const load=()=>{setError('');return dispatcherApi<T>(path).then(setData).catch(e=>setError(e.message))};useEffect(()=>{void load()},[path]);return{data,error,load}}
function Dashboard({go}:{go:(p:DispatcherPage)=>void}){const{data,error,load}=useLoad<DashboardSummary>('/dashboard');const cards:[string,number|undefined,DispatcherPage,string][]=[['Confirmed Orders',data?.confirmed,'orders','Awaiting allocation'],['Planned Orders',data?.planned,'planning','Assigned to trips'],['Deferred Orders',data?.deferred,'deferred','Needs resolution'],['Active Trips',data?.activeTrips,'live','Live operations'],['Available Vehicles',data?.availableVehicles,'fleet','Ready to assign']];return <><section className="dp-hero"><div><small>DELIVERY CONTROL CENTRE</small><h2>Good morning, Dispatcher</h2><p>Review demand, resolve constraints and publish today's delivery plan.</p></div><button onClick={()=>go('orders')}>Review Confirmed Orders <ChevronRight size={16}/></button></section>{error&&<Error text={error} retry={load}/>}<div className="dp-stats">{cards.map(([label,value,page,note])=><button onClick={()=>go(page)} key={label}><small>{label}</small><b>{value??'—'}</b><span>{note}</span><ChevronRight size={16}/></button>)}</div><section className="dp-panel"><h2>Dispatcher Workflow</h2>{[['1','Review confirmed and urgent orders','orders'],['2','Validate vehicle and delivery constraints','planning'],['3','Monitor published delivery trips','live']].map(([n,label,p])=><button className="dp-flow" key={n} onClick={()=>go(p as DispatcherPage)}><b>{n}</b>{label}<ChevronRight size={16}/></button>)}</section></>}
function Orders({go}:{go:(p:DispatcherPage)=>void}){
  const{data=[],error,load}=useLoad<DispatchOrder[]>('/orders');
  const[q,setQ]=useState(''),[detail,setDetail]=useState<DispatchOrder>();
  const[depot,setDepot]=useState('ALL'),[date,setDate]=useState('ALL'),[temperature,setTemperature]=useState('ALL');
  const[access,setAccess]=useState('ALL'),[priority,setPriority]=useState('ALL'),[deferred,setDeferred]=useState('ALL');
  const depots=[...new Set(data.map(order=>order.depot))].sort();
  const dates=[...new Set(data.map(order=>order.windowStart.slice(0,10)))].sort();
  const rows=data.filter(order=>{
    const matchesSearch=(order.reference+order.outletName+order.depot).toLowerCase().includes(q.toLowerCase());
    return matchesSearch&&(depot==='ALL'||order.depot===depot)&&(date==='ALL'||order.windowStart.slice(0,10)===date)
      &&(temperature==='ALL'||order.temperature===temperature)&&(access==='ALL'||(access==='VAN_ONLY'?order.vanOnly:!order.vanOnly))
      &&(priority==='ALL'||(priority==='URGENT'?order.priority>0:order.priority===0))
      &&(deferred==='ALL'||(deferred==='YES'?order.deferralCount>0:order.deferralCount===0));
  });
  const reset=()=>{setQ('');setDepot('ALL');setDate('ALL');setTemperature('ALL');setAccess('ALL');setPriority('ALL');setDeferred('ALL')};
  return <><section className="dp-panel"><Head code="DP-03 · ORDER INTAKE" title="Confirmed Orders Queue" subtitle={`${data.length} orders ready for planning`}><input placeholder="Search order or outlet" value={q} onChange={e=>setQ(e.target.value)}/><button className="light" onClick={load}><RefreshCw size={15}/>Refresh</button><button onClick={()=>go('planning')}>Start Planning</button></Head>{error&&<Error text={error} retry={load}/>}<div className="planning-filters"><label>Depot<select aria-label="Filter by depot" value={depot} onChange={e=>setDepot(e.target.value)}><option value="ALL">All depots</option>{depots.map(value=><option key={value}>{value}</option>)}</select></label><label>Delivery date<select aria-label="Filter by delivery date" value={date} onChange={e=>setDate(e.target.value)}><option value="ALL">All dates</option>{dates.map(value=><option key={value} value={value}>{new Date(`${value}T00:00:00`).toLocaleDateString()}</option>)}</select></label><label>Temperature<select aria-label="Filter by temperature" value={temperature} onChange={e=>setTemperature(e.target.value)}><option value="ALL">All temperatures</option><option>AMBIENT</option><option>CHILLED</option><option>FROZEN</option></select></label><label>Access<select aria-label="Filter by access" value={access} onChange={e=>setAccess(e.target.value)}><option value="ALL">All access</option><option value="VAN_ONLY">Van only</option><option value="STANDARD">Standard access</option></select></label><label>Priority<select aria-label="Filter by priority" value={priority} onChange={e=>setPriority(e.target.value)}><option value="ALL">All priorities</option><option value="URGENT">Urgent</option><option value="STANDARD">Standard</option></select></label><label>Previously deferred<select aria-label="Filter by previous deferral" value={deferred} onChange={e=>setDeferred(e.target.value)}><option value="ALL">All orders</option><option value="YES">Previously deferred</option><option value="NO">Not deferred</option></select></label><div className="filter-summary"><b>Showing {rows.length} of {data.length}</b><button className="light" onClick={reset}>Reset filters</button></div></div><OrderTable orders={rows} view={setDetail}/>{!error&&!rows.length&&<p className="empty-filter">No confirmed orders match these filters.</p>}</section>{detail&&<OrderDetail order={detail} close={()=>setDetail(undefined)}/>}</>}
function OrderTable({orders,view}:{orders:DispatchOrder[];view:(o:DispatchOrder)=>void}){return <div className="dp-table"><div className="row headings"><span>Order / Outlet</span><span>Requirements</span><span>Window</span><span>Load</span><span>Action</span></div>{orders.map(o=><div className="row" key={o.id}><span><b>{o.reference}</b><small>{o.outletName} · {o.depot}</small></span><span className="chips">{o.temperature!=='AMBIENT'&&<i><Snowflake size={12}/>{o.temperature}</i>}{o.vanOnly&&<i>VAN ONLY</i>}</span><span>{time(o.windowStart)}–{time(o.windowEnd)}</span><span>{o.weightKg} kg<small>{o.volumeM3} m³</small></span><span><button className="light" onClick={()=>view(o)}><Eye size={14}/>Details</button></span></div>)}</div>}
function Planning(){const{data:orders=[],error,load}=useLoad<DispatchOrder[]>('/orders');const[selected,setSelected]=useState(new Set<string>()),[detail,setDetail]=useState<DispatchOrder>(),[preview,setPreview]=useState<{results:AllocationResult[];vehicles:DispatchVehicle[]}>(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>setSelected(new Set(orders.map(x=>x.id))),[orders]);const validate=async()=>{setBusy(true);try{setPreview(await dispatcherApi('/plans/preview',{method:'POST',body:JSON.stringify({orderIds:[...selected],serviceDate:tomorrow()})}))}finally{setBusy(false)}};const publish=async()=>{if(!preview||!confirm('Publish this delivery plan?'))return;setBusy(true);try{const result=await dispatcherApi<{trips:number}>('/plans/publish',{method:'POST',body:JSON.stringify({serviceDate:tomorrow(),results:preview.results})});setMessage(`${result.trips} trip(s) published to Loader and Driver workflows.`);setPreview(undefined);await load()}finally{setBusy(false)}};return <>{error&&<Error text={error} retry={load}/>}<section className="dp-panel"><Head code="DP-04 · CONSTRAINT-AWARE ALLOCATION" title="Daily Delivery Planning" subtitle="Weight · volume · refrigeration · access · windows · fuel · two-trip maximum"><button disabled={!selected.size||busy} onClick={validate}>{busy?'Validating…':`Validate & Review ${selected.size}`}</button></Head><div className="plan-list">{orders.map(o=><div key={o.id}><input type="checkbox" checked={selected.has(o.id)} onChange={()=>setSelected(s=>{const n=new Set(s);n.has(o.id)?n.delete(o.id):n.add(o.id);return n})}/><b>{o.reference}</b><span>{o.outletName}</span><small>{o.weightKg} kg · {o.volumeM3} m³</small><button className="light" onClick={()=>setDetail(o)}>Order Details</button></div>)}</div></section>{preview&&<section className="dp-panel review"><Head code="DP-08 · PRE-PUBLISH CHECK" title="Allocation Review" subtitle={`${preview.results.filter(x=>x.status==='SERVED').length} served · ${preview.results.filter(x=>x.status==='DEFERRED').length} deferred`}><button className="light" onClick={()=>setPreview(undefined)}>Correct Plan</button><button onClick={publish}>Publish Delivery Plan</button></Head>{preview.results.map(r=>{const o=orders.find(x=>x.id===r.orderId),v=preview.vehicles.find(x=>x.id===r.assignedVehicleId);return <div className={`result ${r.status.toLowerCase()}`} key={r.orderId}>{r.status==='SERVED'?<CheckCircle2/>:<AlertTriangle/>}<p><b>{o?.reference} · {o?.outletName}</b><small>{r.status==='SERVED'?`${v?.registration} · Trip ${r.tripSequence} · constraints valid`:r.deferralReason}</small></p><i>{r.status}</i></div>})}</section>}{message&&<div className="success">{message}</div>}{detail&&<OrderDetail order={detail} close={()=>setDetail(undefined)}/>}</>}
function Fleet(){const{data=[],error,load}=useLoad<DispatchVehicle[]>('/vehicles');const[detail,setDetail]=useState<DispatchVehicle>();const view=async(v:DispatchVehicle)=>setDetail(await dispatcherApi(`/vehicles/${v.id}`));return <><Head code="DP-06 · FLEET CONTROL" title="Fleet & Vehicles" subtitle={`${data.length} vehicles across the Peliyagoda delivery network`}><button className="light" onClick={load}><RefreshCw size={15}/>Refresh</button></Head>{error&&<Error text={error} retry={load}/>}<div className="fleet-grid">{data.map(v=><article key={v.id}><div><Truck/><i>{v.available?'AVAILABLE':'MAINTENANCE'}</i></div><h3>{v.registration}</h3><p>{v.type} · {v.depot}{v.refrigerated?' · Refrigerated':''}</p><dl><span>Payload<b>{v.maxWeightKg.toLocaleString()} kg</b></span><span>Volume<b>{v.maxVolumeM3} m³</b></span></dl><label>Weekly fuel<progress value={v.fuelUsedThisWeekL} max={v.weeklyFuelQuotaL}/><small>{v.fuelUsedThisWeekL} / {v.weeklyFuelQuotaL} L · {v.tripsToday}/2 trips</small></label><button className="light full" onClick={()=>view(v)}>View Capacity Details</button></article>)}</div>{detail&&<VehicleDetail vehicle={detail} close={()=>setDetail(undefined)}/>}</>}
function Deferred(){const{data=[],error,load}=useLoad<DispatchOrder[]>('/orders?status=DEFERRED');const[edit,setEdit]=useState<DispatchOrder>(),[reason,setReason]=useState('');const save=async()=>{if(!edit||!reason.trim())return;await dispatcherApi(`/deferred/${edit.id}`,{method:'PATCH',body:JSON.stringify({reason})});setEdit(undefined);await load()};return <section className="dp-panel"><Head code="DP-09 · EXCEPTION MANAGEMENT" title="Deferred Orders" subtitle="Reason, next delivery slot and repeat-deferral risk"><button className="light" onClick={load}>Refresh Queue</button></Head>{error&&<Error text={error} retry={load}/>}<div className="deferred-list">{data.map(o=><article key={o.id}><AlertTriangle/><p><b>{o.reference} · {o.outletName}</b><small>{o.deferralReason||'Reason required'}</small></p><span><small>NEXT SLOT</small><b>Tomorrow · Morning</b></span><span><small>REPEAT RISK</small><b>{o.deferralCount?`${o.deferralCount} previous · High`:'First · Low'}</b></span><button className="light" onClick={()=>{setEdit(o);setReason(o.deferralReason||'')}}>Configure</button></article>)}</div>{edit&&<Modal title={`Deferral Protocol · ${edit.reference}`} close={()=>setEdit(undefined)}><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required deferral reason"/><button onClick={save}>Save Resolution</button></Modal>}</section>}
function Live(){const{data=[],error,load}=useLoad<DispatchTrip[]>('/trips');const[open,setOpen]=useState<string>(),[detail,setDetail]=useState<DispatchTrip>();return <><section className="dp-panel"><Head code="DP-10 · LIVE OPERATIONS" title="Active Delivery Progress" subtitle="Trip progress, stop status, ETAs and operational issues"><button className="light" onClick={load}>Refresh Telemetry</button></Head>{error&&<Error text={error} retry={load}/>} {data.map(t=><article className="trip" key={t.id}><button onClick={()=>setOpen(open===t.id?undefined:t.id)}><Route/><p><b>{t.reference}</b><small>{t.vehicle.registration} · {t.driver} · {t.stops.length} stops</small></p><i>{t.status}</i><ChevronRight/></button>{open===t.id&&<><div className="stops">{t.stops.map(s=><span key={s.id}><b>{s.sequence}</b>{s.order.outletName}<small>{time(s.eta)} · {s.status}</small></span>)}</div><button className="telematics" onClick={()=>setDetail(t)}>View Full Trip Telematics</button></>}</article>)}</section>{detail&&<TripDetail trip={detail} close={()=>setDetail(undefined)}/>}</>}
function Head({code,title,subtitle,children}:{code:string;title:string;subtitle:string;children?:React.ReactNode}){return <div className="dp-head"><div><small>{code}</small><h2>{title}</h2><p>{subtitle}</p></div><div>{children}</div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><header><h2>{title}</h2><button onClick={close}><X/></button></header>{children}</section></div>}
function OrderDetail({order,close}:{order:DispatchOrder;close:()=>void}){return <Modal title={`Order Details · ${order.reference}`} close={close}><Detail values={[['Outlet',order.outletName],['Depot',order.depot],['Address',order.address],['Delivery window',`${time(order.windowStart)}–${time(order.windowEnd)}`],['Weight',`${order.weightKg} kg`],['Volume',`${order.volumeM3} m³`],['Temperature',order.temperature],['Access',order.vanOnly?'Van only':'Standard']]}/></Modal>}
function VehicleDetail({vehicle:v,close}:{vehicle:DispatchVehicle;close:()=>void}){return <Modal title={`Vehicle Capacity · ${v.registration}`} close={close}><Detail values={[['Status',v.status||'AVAILABLE'],['Type',v.type],['Depot',v.depotId||v.depot],['Temperature',v.refrigerated?'Refrigerated':'Ambient'],['Weight utilization',`${v.usedWeightKg||0} / ${v.maxWeightKg} kg`],['Volume utilization',`${v.usedVolumeM3||0} / ${v.maxVolumeM3} m³`],['Route',v.route?.reference||'Not assigned'],['Driver',v.route?.driver||'Not assigned']]}/><div className="stops vertical">{v.assignedStops?.map(s=><span key={s.sequence}><b>{s.sequence}</b>{s.order} · {s.outlet}</span>)}</div></Modal>}
function TripDetail({trip:t,close}:{trip:DispatchTrip;close:()=>void}){return <Modal title={`Trip Monitoring · ${t.reference}`} close={close}><Detail values={[['Driver',t.driver],['Vehicle',t.vehicle.registration],['Status',t.status],['Stops',String(t.stops.length)],['Cold-chain',t.coldChain],['Issues',t.issues.length?t.issues.join(', '):'No active issues']]}/><div className="stops vertical">{t.stops.map(s=><span key={s.id}><b>{s.sequence}</b>{s.order.reference} · {s.order.outletName}<small>{time(s.eta)} · {s.status}</small></span>)}</div></Modal>}
function Detail({values}:{values:[string,string][]}){return <div className="details">{values.map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div>}
function Error({text,retry}:{text:string;retry:()=>unknown}){return <div className="error">{text}<button onClick={retry}>Try again</button></div>}
